version: 0.1

phases:
  build:
    commands:
      - npm cache clean --force
      - npm cache verify
      - npm install
      - npm i -g webpack
      - npm run buildproduction
      - rm -rf node_modules package-lock.json coverage build .DS_Store .env.local .env.development.local .env.test.local .env.production.local yarn-debug.log* yarn-error.log* *.orig .elasticbeanstalk
      - printenv
artifacts:
  files:
    - '**/*'
